openapi: 3.0.1

info:
  title: ChatGPT Plugin ToDo API
  version: 1.0.0
  description: API Specification for chatGPT Plugin ToDo API

paths:
  /todos:
    get:
      summary: get all todos
      operationId: getTodos
      tags:
        - todos
      responses:
        '200':
          description: Succesful response
          content:
            applicatioin/json:
              schema:
                type: object
                properties:
                  todos:
                    type: array
                    items:
                      $ref: '#/components/schemas/Todo'
    post:
      summary: Create a todo
      operationId: createTodo
      tags:
        - todos
      requestBody:
        required: true
        description: Todo object to be created
        content:
          application/json:
            schema:
              $href: '#/components/schemas/TodoInput'
      responses:
        '200':
          description: Succesful response
          content:
            application/json:
              schema:
              $ref: '#/components/schemas/Todo'
  /todos/{id}:
    get:
      summary: get a todo by id
      operationId: getTodo
      tags:
        - todos
      parameters:
        - name: id
          in: path
          required: true
          description: Id of the todo to be retrieved
            schema:
              type: string
      responses:
        '200:'
          description: succesfun response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    put:
      summary: Update a todo by id
      operationId: updateTodo
      tags:
        - todos
      parameters:
        - name: id
        in: path
        required: true
        description: id of the todo to be updated
        schema:
          type: string
      requestBody:
          required: true
          description: Todo object to be updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoInput'
      responses:
        '200':
          description: succesful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    delete:
      summary: Delete a todo by id
      operationId: deleteTodo
      tags:
        - todos
      parameters:
        - name: id
          in: path
          required: true
          description: Id of the todo to be deleted
          schema:
            type: string
      responses:
        '200':
          description: Succesful response
          content:
            aplication/json:
              type: object
              properties:
                ok:
                  type: boolean
                  
