openapi: 3.0.1

info:
  title: ChatGPT Plugin ToDo API
  version: 1.0.0
  description: API Specification for chatGPT Plugin ToDo API

paths:
  /todos:
    get:
      summary: get all todos
      operationId: getTodos
      tags:
        - todos
      responses:
        '200':
          description: Succesful response
          content:
            applicatioin/json:
              schema:
                type: object
                properties:
                  todos:
                    type: array
                    items:
                      $ref: '#/components/schemas/Todo'
    post:
      summary: Create a todo
      operationId: createTodo
      tags:
        - todos
      requestBody:
        required: true
        description: Todo object to be created
        content:
          application/json:
            schema:
              $href: '#/components/schemas/TodoInput'
      responses:
        '200':
          description: Succesful response
          content:
            application/json:
              schema:
              $ref: '#/components/schemas/Todo'
    delete:
      summary: Delete all todos
      operationId: deleteTodos
      tags:
        - todos
      responses:
        '200':
          description: Succesful response
          content:
            aplication/json:
              schema:
                type: object
                properties:
                  todos:
                    type: array
                    items:
                      $ref: '#/components/schemas/Todo'
